### ISSUE TITLE
Unable to reproduce CIFAR-10 results

### ISSUE THREAD

**Issue by stevenwalton** [matejgrcic/DenseFlow#2]
Hi, I'm having a hard time reproducing the CIFAR-10 results (haven't tried others yet). I am more consistently getting around 3.1bpd on the eval set and can get around 2.9bpd on the training set. I've even tried training longer and different scheduling than is described in the appendix. Was this the best result that you got or an average? Do you have a variance? Do you have a checkpoint that could be released?

**Comment by matejgrcic** [comment]
Hi, checkpoints are already open-sourced.
You can find the download link on the README page under [Model weights](https://github.com/matejgrcic/DenseFlow#model-weights) section.
