### ISSUE TITLE
Producing images of higher resolution

### ISSUE THREAD

**Issue by mbisan** [matejgrcic/DenseFlow#6]
Hi, I'm wondering how to produce samples of different sizes. Since the latent representation for the imagenet64 model is (308, 8, 8), I tried sampling from a vector of size (308, 16, 16), which produces images with dimensions (3, 128, 128) as I expected, but this output is quite bad. I'm using the pretrained weights.

![image](https://user-images.githubusercontent.com/36307382/223385856-edcf2f06-3fb0-4907-b05a-b9e35d565882.png)

**Comment by matejgrcic** [comment]
This seems odd. Perhaps a smaller model would have a more stable inverse.

**Comment by mbisan** [comment]
Hi, thanks for the response. This is what I tried to do:

In the class defined in [flow.py](https://github.com/matejgrcic/DenseFlow/blob/main/denseflow/flows/flow.py) I added the following method:

```
def sample_with_shape(self, num_samples, shape):
    self.base_dist.shape = shape
    z = self.base_dist.sample(num_samples)
    for transform in reversed(self.transforms):
        z = transform.inverse(z)
    return z
```
Basically the same but producing a noise vector with different dimensions.

Then I use the function like this:

`img = model.sample_with_shape(1, (308, 16, 16))
`

I don't have much insight into what exactly is going on inside the model, so I'm not sure If this is the correct way to do this.

P.S. In order to reproduce my behavior, I did this from start to end:

```
model = DenseFlow(data_shape=(3, 64, 64),
                block_config=(6, 4, 1),
                layers_config=(5, 6, 20),
                layer_mid_chnls=(48, 48, 48),
                growth_rate=10)
loaded = torch.load("path to imagenet weights")
model.load_state_dict(loaded["model"])
img = model.sample_with_shape(1, (308, 16, 16))
plt.imshow(np.transpose(img[0].numpy(), (1,2,0)))
```

**Comment by mbisan** [comment]
I got a smaller DenseFlow-25-6 model to produce similar images at different resolutions:

```
DenseFlow(data_shape=(3, 64, 64),
            block_config=(3, 2, 1),
            layers_config=(3, 3, 10),
            layer_mid_chnls=(48, 48, 48),
            growth_rate=6)
```

Example:

![image](https://user-images.githubusercontent.com/36307382/227150743-ca2facfb-9038-46ab-aa49-8ac1953ec9bd.png)
